// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwwjMdYFuEJmZshLZYsVkI-oRdUX5Q-IM',
    appId: '1:483247968191:web:e04a2ba76cca541688db0a',
    messagingSenderId: '483247968191',
    projectId: 'fetch-222d4',
    authDomain: 'fetch-222d4.firebaseapp.com',
    storageBucket: 'fetch-222d4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3ujFbsesdPGZIWTlHW24Iwsy3s6eGbjk',
    appId: '1:483247968191:android:745d0c964a4bbec988db0a',
    messagingSenderId: '483247968191',
    projectId: 'fetch-222d4',
    storageBucket: 'fetch-222d4.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI1_6lRSsRENPbMAgeelOUhVNB9qNsAjs',
    appId: '1:483247968191:ios:136fad41382fa7aa88db0a',
    messagingSenderId: '483247968191',
    projectId: 'fetch-222d4',
    storageBucket: 'fetch-222d4.appspot.com',
    iosBundleId: 'com.example.fetch',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI1_6lRSsRENPbMAgeelOUhVNB9qNsAjs',
    appId: '1:483247968191:ios:136fad41382fa7aa88db0a',
    messagingSenderId: '483247968191',
    projectId: 'fetch-222d4',
    storageBucket: 'fetch-222d4.appspot.com',
    iosBundleId: 'com.example.fetch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwwjMdYFuEJmZshLZYsVkI-oRdUX5Q-IM',
    appId: '1:483247968191:web:e8bd8f5cf9f2db9488db0a',
    messagingSenderId: '483247968191',
    projectId: 'fetch-222d4',
    authDomain: 'fetch-222d4.firebaseapp.com',
    storageBucket: 'fetch-222d4.appspot.com',
  );

}